### ISSUE TITLE
看不到二维码，加不了

### ISSUE THREAD

**Issue by baiyapeng228** [jujunchen/ebook#3]

**Comment by jujunchen** [comment]
可以了

**Comment by jujunchen** [comment]
有需要关注公众号itsaysay(阿提说说)，发送下面列出的书名获取对应地址，如果我看到了没有返回地址，会手动回复

已经关注，下载完的，不要取消了吧，好歹我辛苦搜集，再说我公众号也没有广告，想到了就给大家分享分享干货

阿提说说
