### ISSUE TITLE
就不能简单点 关注这关注那的。。

### ISSUE THREAD

**Issue by Pan-zc** [jujunchen/ebook#4]
就不能简单点 关注这关注那的。。

**Comment by jujunchen** [comment]
直接发不上来的

在 2021-10-25 23:31:25，18-air ***@***.***> 写道：


就不能简单点 关注这关注那的。。

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
